# Generated by Django 4.0.3 on 2022-05-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_student_customerproxy_alter_customer_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
    ]
