# Generated by Django 4.0.3 on 2022-06-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price_unit',
            new_name='unit_price',
        ),
    ]
