
services:
  backend:
    build:
      context: .
    env_file:
      - deployment/app-server/app-server.env
    ports:
      - 8000:8000
    entrypoint: gunicorn -c gunicorn.conf.py onlineshop.wsgi:application
    networks:
      - backend-tier
    depends_on:
      - nginx
    restart: on-failure:5

  nginx: 
    image: dockerhub.ir/nginx
    ports:
      - 9999:9999
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./public:/public
    networks:
      - backend-tier
    restart: on-failure:5

  postgres:
    image: dockerhub.ir/postgres
    env_file:
      - deployment/postgres/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./seed.sql:/seed.sql
    networks:
      - backend-tier
    depends_on:
      - backend
    restart: on-failure:5


networks:
  backend-tier:
    driver: bridge

volumes:
  postgres-data: null