# Generated by Django 4.0.3 on 2022-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_collection_product_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrition', models.TextField()),
                ('discount', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ManyToManyField(to='store.promotion'),
        ),
    ]
