# Generated by Django 4.0.3 on 2022-03-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_promotion_product_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_field', models.CharField(max_length=255)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product2')),
                ('promotion_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.promotion')),
            ],
        ),
        migrations.AddField(
            model_name='product2',
            name='promotion',
            field=models.ManyToManyField(through='store.PromotionProduct', to='store.promotion'),
        ),
    ]
